# Generated by Django 5.2 on 2026-05-07 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_page', models.CharField(max_length=120)),
                ('event_type', models.CharField(choices=[('whatsapp_click', 'Click en WhatsApp'), ('detail_view', 'Vista de detalle')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_events', to='directory.provider')),
            ],
            options={
                'verbose_name': 'evento de lead',
                'verbose_name_plural': 'eventos de leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
