# Generated by Django 6.0.5 on 2026-09-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spam_flag',
            field=models.BooleanField(default=False, help_text='El registro disparó el filtro antispam.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spam_reasons',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
