# Generated by Django 5.2 on 2026-05-07 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Nombre corto o emoji visible.', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'comuna',
                'verbose_name_plural': 'comunas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('contact_name', models.CharField(max_length=120)),
                ('sector', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=220)),
                ('phone', models.CharField(max_length=30)),
                ('whatsapp_number', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=180)),
                ('service_area', models.CharField(blank=True, max_length=180)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('whatsapp_clicks_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='directory.category')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='directory.commune')),
            ],
            options={
                'verbose_name': 'prestador',
                'verbose_name_plural': 'prestadores',
                'ordering': ['-is_featured', '-is_verified', 'business_name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='providers/')),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('is_cover', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='directory.provider')),
            ],
            options={
                'verbose_name': 'imagen de prestador',
                'verbose_name_plural': 'imagenes de prestadores',
                'ordering': ['display_order', '-is_cover', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['is_active', 'is_featured', 'is_verified'], name='directory_p_is_acti_acb982_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['slug'], name='directory_p_slug_adefea_idx'),
        ),
    ]
