# Generated by Django 5.2 on 2026-05-07 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(max_length=140)),
                ('nombre_contacto', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(max_length=30)),
                ('sector', models.CharField(max_length=120)),
                ('descripcion_servicio', models.TextField()),
                ('acepta_contacto', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('contactado', 'Contactado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='directory.category')),
            ],
            options={
                'verbose_name': 'postulacion de prestador',
                'verbose_name_plural': 'postulaciones de prestadores',
                'ordering': ['-created_at'],
            },
        ),
    ]
