# Generated by Django 5.2 on 2026-05-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_providerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerapplication',
            name='anos_experiencia',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='horario_atencion',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='instagram',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
