# Generated by Django 5.2 on 2026-05-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_providerapplication_anos_experiencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='data_status',
            field=models.CharField(choices=[('prospecto_publico', 'Prospecto publico'), ('contactado', 'Contactado'), ('autorizado', 'Autorizado'), ('rechazado', 'Rechazado')], default='prospecto_publico', max_length=30),
        ),
        migrations.AddField(
            model_name='provider',
            name='source_name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='provider',
            name='source_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
