# Generated by Django 5.2 on 2026-05-07 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_provider_data_status_provider_source_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regiones',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['is_active', 'commune', 'category'], name='directory_p_is_acti_38174e_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['is_active', 'data_status'], name='directory_p_is_acti_8a76a1_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['business_name'], name='directory_p_busines_cabc55_idx'),
        ),
        migrations.AddField(
            model_name='commune',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communes', to='directory.region'),
        ),
    ]
