# Generated by Django 6.0.5 on 2026-09-04 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_provider_claimed_at_provider_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='moderation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='spam_flag',
            field=models.BooleanField(default=False, help_text='Marcado por el filtro antispam al publicar. Se guarda igual; un moderador decide.'),
        ),
        migrations.AddField(
            model_name='provider',
            name='spam_reasons',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ProviderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reporte', 'Reportar perfil'), ('baja', 'Solicitar baja (soy el titular)'), ('correccion', 'Corregir datos')], default='reporte', max_length=20)),
                ('reporter_name', models.CharField(blank=True, max_length=120)),
                ('reporter_contact', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField()),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('spam_flag', models.BooleanField(default=False)),
                ('spam_reasons', models.CharField(blank=True, max_length=200)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='directory.provider')),
            ],
            options={
                'verbose_name': 'reporte de perfil',
                'verbose_name_plural': 'reportes de perfiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
